title: Amirhossein Habibian
position: Research Scientist
affiliation: Qualcomm AI Research
email: habibian@qti.qualcomm.com
keywords: deep learning
google_scholar: https://scholar.google.com/citations?user=RZ9pOY4AAAAJ&hl=en/
github_link: https://github.com/
linkedin: https://nl.linkedin.com/in/amirhossein-habibian-30a39135
avatar: ./assets/img/amir.jpg
google_analytics: UA-111540567-4
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon-dark.png
description: Homepage of Amirhossein Habibian
canonical: https://habibian.github.io/
remote_theme: yaoyao-liu/minimal-light
